spheres = <<-string

All 
Bless (1st)
Combine (1st)
Detect Evil (1st)
Purify Food & Drink (1st)
Atonement (5th)

Animal 
Animal Friendship (1st) 
Invisibility to Animals (1st) 
Locate Animals or Plants (1st) 
Charm Person or Mammal (2nd) 
Messenger (2nd) 
Snake Charm (2nd) 
Speak With Animals (2nd) 
Hold Animal (3rd) 
Summon Insects (3rd) 
Animal Summoning I (4th) 
Call Woodland Beings (4th) 
Giant Insect (4th) 
Repel Insects (4th) 
Animal Growth (5th) 
Animal Summoning II (5th) 
Animal Summoning III (6th) 
Anti-Animal Shell (6th) 
Geeping Doom (7th)

Astral 
Plane Shift (5th) 
Astral Spell (7th) 

Charm 
Command (1st) 
Remove Fear (1st) 
Enthrall (2nd) 
Hold Person (2nd) 
Cloak of Bravery (4th) 
Free Action (4th) 
Imbue With Spell Ability (4th) 
Quest (5th) 
Cumfusion (7th) 
Exaction (7th)

Combat 
Magical Stone (1st) 
Shillelagh (1st) 
Chant (2nd) 
Spiritual Hammer (2nd) 
Prayer (3rd) 
Flame Strike (5th) 
Insect Plague (5th) 
Holy Word (7th) 

Creation 
Create Food & Water (3rd) 
Animate Object (6th) 
Blade Barrier (6th) 
Heroes’ Feast (6th) 
Wall of Thorns (6th) 
Changestaff (7th) 
Chariot of Sustarre (7th) 

Divination 
Detect Magic (1st) 
Detect Poison (1st) 
Detect Snares & Pits (1st) 
Locate Animals or Plants (1st) 
Augury (2nd) 
Detect Charm (2nd) 
Find Traps (2nd) 
Know Alignment (2nd) 
Speak With Animals (2nd) 
Locate Object (3rd) 
Speak With Dead (3rd) 
Detect Lie (4th) 
Divination (4th) 
Reflecting Pool (4th) 
Tongues (4th) 
Commune (5th) 
Commune With Nature (5th) 
Magic Font (5th) 
True Seeing (5th) 
Find the Path (6th) 
Speak With Monsters (6th)

Elemental 
Create Water (1st) 
Dust Devil (2nd) 
Fire Trap (2nd) 
Flame Blade (2nd) 
Heat Metal (2nd) 
Produce Flame (2nd) 
Flame Walk (3rd) 
Meld Into Stone (3rd) 
Protections From Fire (3rd) 
Pyrotechnics (3rd) 
Stone Shape (3rd) 
Water Breathing (3rd) 
Water Walk (3rd) 
Lower Water (4th) 
Produce Fire (4th)
Air Walk (5th)
Spike Stones (5th) 
Transmute Rock to Mud (5th) 
Wall of Fire (5th) 
Conjure Fire Elemental (6th) 
Fire Seeds (6th) 
Part Water (6th) 
Stone Tell (6th) 
Transmute Water to Dust (6th) 
Animate Rock (7th) 
Chariot of Sustarre (7th) 
Conjure Earth Elemental (7th) 
Earthquake (7th) 
Fie Storm (7th)
Transmute Metal to Wood (7th) 
Wind Walk (7th)

Guardian 
Silence, 15’ Radius (2nd) 
Wyvern Watch (2nd) 
Glyph of Warding (3rd) 
Blade Barrier (6th) 
Symbol (7th)

Healing 
Cure Light Wounas tist) 
Slow Poison (2nd) 
Cure Serious Wounds (4th) 
Neutralize Poison (4th) 
Cure Critical Wounds (5th) 
Heal (6th)

Necromantic 
Invisibility to Undead (1st) 
Aid (2nd) 
Animate Dead (3rd) 
Cure Blindness or Deafness (3rd) 
Cure Disease (3rd) 
Feign Death (3rd) 
Negative Plane Protection (3rd) 
Raise Dead (5th) 
Regenerate (7th) 
Reincarnate (7th) 
Restoration (7th) 
Resurrection (7th)

Plant 
Entangle (1st) 
Pass Without Trace (1st) 
Shillelagh (1st) 
Barkskin (2nd) 
Goodberry (2nd) 
Trip (2nd)
Warp Wood (2nd)
Plant Growth (3rd) 
Snare (3rd) 
Spike Growth (3rd) 
Tree (3rd) 
Hallucinatory Forest (4th) 
Hold Plant (4th) 
Plant Door (4th) 
Speak With Plants (4th) 
Sticks to Snakes (4th) 
Anti-Plant Shell (5th) 
Pass Plant (5th) 
Liveoak (6th) 
Transport Via Plants (6th) 
Turn Wood (6th) 
Wall of Thorns (6th) 
Channestaff (7th)

Protection 
Endure Cold/Endure Heat (1st) 
Protection From Evil (1st) 
sanctuary (1st) 
Barkskin (2nd) 
Resist Fire/Resist Cold (2nd) 
Withdraw (2nd) 
Dispel Magic (3rd) 
Magical Vestment (3rd) 
Negative Plane Protection (3rd) 
Protection From Fire (3rd) 
Remove Curse (3rd) 
Remove Paralysis (3rd) 
Protection From Evil, 10"'" Evil (4th) 
Protection From Lightning (4th) 
Repel Insects (4th) 
SpeU Immunity (4th) 
Anti-Plant Shell (5th) 
Dispel Evil (5th) 
Anti-Animal Shell (6th)

Summoning 
Abjure (4th) 
Animal Summoning I (4th) 
Call Woodland Beings (4th) 
Animal Summoning I1 (5th) 
Dispel Evil (5th) 
Aerial Servant (6th) 
Animal Summoning I11 (6th) 
Animate Object (6th) 
Conjure Animals (6th) 
Wall of Thorns (6th) 
Weather Summoning (6th) 
Word of Recall (6th) 
Conjure Earth Elemental (7th) 
Creeping Doom (7th) 
Exaction (7th) 
Gate (7th) 
Succor (7th)

Sun 
Light (1st) 
Continual Light (3rd) 
Starshine (3rd) 
Moonbeam (5th) 
Rainbow (5th) 
Sunray (7th) 

Weather 
Faerie Fire (1st) 
Obscurement (2nd) 
Call Lightning (3rd) 
Control Temperature, 10"'" Radius (4th) 
Protection From Lightning (4th) 
Control Winds (5th) 
Rainbow (5th) 
Weather Summoning (6th) 
Control Weather (7th)
string
